### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by maitri-vv** [dev-AshishRanjan/Hacktoberfest-Frontend#11]
Raising a new issue with a PR as earlier changes i did was overwritten and enhanced already by someone

screenshot: 
![WhatsApp Image 2023-10-07 at 14 56 36_559ec0cc](https://github.com/dev-AshishRanjan/Hacktoberfest-Frontend/assets/87691594/167bfddf-8cbe-4d60-964f-a18cc35df9cb)

the history of searched items were visible so i disabled it and also centered the form properly
Raising PR again for this, kindly review

**Comment by dev-AshishRanjan** [comment]
cloasing as new issues generated
