### ISSUE TITLE
Contact page 

### ISSUE THREAD

**Issue by Aka-suvam** [dev-AshishRanjan/Hacktoberfest-Frontend#16]
In the Contact page of your project (FrontEnd Database) . the User can  also  submit  the Empty form .  i make sure  that  Contact form  must be filled out before submitting the form.  
if the issue valid or okk for you . i  like to work on this issue under the  label of - hacktoberfest,  hacktoberfest2023 .  

Also added video of the issue below . 

[screen-capture.webm](https://github.com/dev-AshishRanjan/Hacktoberfest-Frontend/assets/94453074/6762fdd1-04b1-4758-8c4a-46c16b27db15)

**Comment by dev-AshishRanjan** [comment]
@Aka-suvam ,
I have assigned the issue to you

**Comment by dev-AshishRanjan** [comment]
@Aka-suvam 
some people may also be working on this repo, but not on this issue
so please pull before push, to avoid any merge conflits (in any files) 👍🏽

steps :
1. made changes
2. commit
3. pull : `git pull origin dev`
4. push

**Comment by Kedarnath-Rothe** [comment]
Please assign this task to me under hactoberfest label

**Comment by dev-AshishRanjan** [comment]
closed by #29

**Comment by dev-AshishRanjan** [comment]
> Please assign this task to me under hactoberfest label

@Kedarnath-Rothe ,
this issue has been resolved.  

 You can 
1. either create a new issue and work on that issue
2. add a new project by following the guidelines  : https://github.com/dev-AshishRanjan/Hacktoberfest-Frontend/blob/dev/CONTRIBUTING.md
