### ISSUE TITLE
Adding Weather Web Application

### ISSUE THREAD

**Issue by Sujal-2820** [dev-AshishRanjan/Hacktoberfest-frontend#20]
I want to contribute to this repository by adding a Weather Application made with HTML, CSS, JS.

@dev-AshishRanjan please add "Hacktoberfest" labels to it and assign this issue to me 🙂

Thanks!!

**Comment by Upendra2003** [comment]
Hey @dev-AshishRanjan can you assign this to me I would like to do this.

**Comment by Sujal-2820** [comment]
I'll be adding a PR on this issue by this evening itself 🧑‍💻

**Comment by dev-AshishRanjan** [comment]
> Hey @dev-AshishRanjan can you assign this to me I would like to do this.

@Upendra2003 , you can always create a new issue for weather application 👍🏽or any projects
