### ISSUE TITLE
QR Code generator

### ISSUE THREAD

**Issue by Ejay02** [dev-AshishRanjan/Hacktoberfest-frontend#25]
I want to add Qr code generator.
Pls add necessary tag and assign to me.

**Comment by dev-AshishRanjan** [comment]
Please go through the guideline on steps to contribute before contributing : https://github.com/dev-AshishRanjan/Hacktoberfest-frontend/blob/dev/CONTRIBUTING.md

Happy Contributing!

**Comment by dev-AshishRanjan** [comment]
Closing as completed 👨‍💻
