### ISSUE TITLE
[Announcement 📢] : This repo has been re-initialized with all contributions intact

### ISSUE THREAD

**Issue by dev-AshishRanjan** [dev-AshishRanjan/Hacktoberfest-Frontend#3]
Hi contributors,
**This Repository follows all the guidelines provided by Hacktoberfest**

Previously one of my repo didn't follow the guideline : [hacktoberfest2023](https://github.com/dev-AshishRanjan/hacktoberfest2023)
which is a beginner hello world starter repo,
Due to that beginner repo, this repo was excluded from hacktoberfest,
_Now I have removed  [hacktoberfest2023](https://github.com/dev-AshishRanjan/hacktoberfest2023) from Hacktoberfest myself._

Now this and any other of mine's repository (participating in hacktoberfest) follows the hacktoberfest guideline.
**This repo is currently accepted in the Hacktoberfest2023**
If this repo get excluded in future, then we will reach out to organizers, but it's exclusion chances are slim.  

**This repository will never be deleted and re-initialized in future under any circumstances, as we are creating an important database**
So feel free to contribute here by following this repo contribution guideline : [contributing](https://github.com/dev-AshishRanjan/Hacktoberfest-Frontend/blob/dev/CONTRIBUTING.md)

Thanks for consideration, give this repo a star ⭐

**Comment by dev-AshishRanjan** [comment]
@all, @contributors
To all those who contributed in the past as of today,

Yours commits are still there, but that will not be considered for hacktoberfest2023
**You have to fork this ([Hacktoberfest-Frontend](https://github.com/dev-AshishRanjan/Hacktoberfest-Frontend)) repository and make new non-breaking contributions (PRs) again.**  

Sorry for all the inconvenience.

**Comment by dev-AshishRanjan** [comment]
> @ALL, @contributors To all those who contributed in the past as of today,
> 
> Yours commits are still there, but that will not be considered for hacktoberfest2023 **You have to fork this ([Hacktoberfest-Frontend](https://github.com/dev-AshishRanjan/Hacktoberfest-Frontend)) repository and make new non-breaking contributions (PRs) again.**
> 
> Sorry for all the inconvenience.




@EniolaAdemola @ro78ldt @Chinmayee7697 @kshitizvardhan @Sonal144 @Vishal35679 @Avibtb @Mefisto04 @ImgBotApp @AkshitaS10 @oyejateen @Mandeep-009 @omsali @shivanshsin0203 @yash19sinha @Shu4bham @Thalmonn @Vishal2002 @freshBakedPie314 @akanshbende @AniketTewari @pandeydhruv2001 @Ejay02 @HardikPanwar @s-bhalode @Sujal-12345 @Sumedhbhat @krishna050702 @maitri-vv

**Comment by dhruvpal05** [comment]
Hi, @dev-AshishRanjan I don't know why my PR got merged but now it is not showing. [#72](https://github.com/dev-AshishRanjan/Hacktoberfest-Frontend/issues/72#issuecomment-1751610470)

**Comment by Ejay02** [comment]
So we have to add new contributions [projects]? hmm

**Comment by dev-AshishRanjan** [comment]
> So we have to add new contributions [projects]? hmm

Yes you can add new project like doing a new contribution
OR if there is any bug on other's project, then you can correct it.

**Comment by dev-AshishRanjan** [comment]
> Hi, @dev-AshishRanjan I don't know why my PR got merged but now it is not showing. [#72](https://github.com/dev-AshishRanjan/Hacktoberfest-Frontend/issues/72#issuecomment-1751610470)

Hi, @dhruvpal05 
Your commits came after the prev repo was excluded

Now you can do the same contribution again, this time it will be considered

**Comment by pandeydhruv2001** [comment]
Did some modifications in previous thing, please merge the pull request

**Comment by pandeydhruv2001** [comment]
Added a new project also! Please merge the pull request
