### ISSUE TITLE
Update: QR Code generator

### ISSUE THREAD

**Issue by Ejay02** [dev-AshishRanjan/Hacktoberfest-Frontend#32]
wanna add following updates:

- clear after 10seconds,
- add the ability to download QR code.

pls assign it to me and add necessary labels.

**Comment by dev-AshishRanjan** [comment]
@Ejay02 
some people may also be working on this repo, **_but not on this issue_**
so please **_pull before push_**, to avoid any merge conflits (in any files) 👍🏽

steps :
1. made changes
2. commit
3. pull : `git pull origin dev`
4. push
