### ISSUE TITLE
ADD : Project

### ISSUE THREAD

**Issue by dev-AshishRanjan** [dev-AshishRanjan/Hacktoberfest-Frontend#38]
Please follow the Contribution Guideline present in : https://github.com/dev-AshishRanjan/Hacktoberfest-Frontend/blob/dev/CONTRIBUTING.md

To Do :
1. ADD the project files in `projects`.  
2. ADD your project details in `contribution/ProjectList.json` 

This is a beginner friendly repo, a project database in creation.  
Project should be in HTML+CSS/SASS+JS

**Comment by MuhammadSarimWaseem** [comment]
i want to contribute in it

**Comment by nikunjgupta609** [comment]
@dev-AshishRanjan Please sir assign me this issue.

**Comment by suma30** [comment]
@dev-AshishRanjan Can i contribute to this repo by adding a very simple project in html and css (registration form)
Please reply

**Comment by dhruvpal05** [comment]
@dev-AshishRanjan  why this repo is not a part of hacktoberfest, can you suggest me some other repos to contribute??

**Comment by dev-AshishRanjan** [comment]
@dhruvpal05 ,
This repo has been excluded from hacktoberfest
After approaching them, they said it's been decided because it's easy to make a PR in this repo
Don't know why they are considering The Algorithm repo but not this one.

As far as i know any repo with `hacktoberfest` word in their name is under evaluation.

**Comment by dev-AshishRanjan** [comment]
You can also checkout our [Idea-Arca](https://github.com/dev-AshishRanjan/Idea-Arca), the project idea bank for any languages, for open-source contributions.
The PR form this repo is being accepted.

Happy Contributing season!
Keep up the good work!

**Comment by dev-AshishRanjan** [comment]
You can contribute to any repo which doesn't have `hacktoberfest` in their name, but in topic

**Comment by Rajshree097** [comment]
plz assign this issue to me..I have already created the pr @dev-AshishRanjan
