### ISSUE TITLE
Some edits need to be done on Readme 

### ISSUE THREAD

**Issue by dhruvpal05** [dev-AshishRanjan/Hacktoberfest-Frontend#45]
In the 1st step of Process of contribution:
It has git clone https://github.com/dev-AshishRanjan/Hacktoberfest-Frontend.git
Instead of this it should be https://github.com/[username]/Hacktoberfest-Frontend.git
Because it would be better to clone the forked repo instead of the main repo.

In Process of contribution before 3rd step for Create a new Branch (git checkout -b my-new-branch), there should be a step to get into Hacktoberfest-Frontend (cd Hacktoberfest-Frontend) otherwise it shows  fatal: not a git repository (or any of the parent directories)

**Comment by dev-AshishRanjan** [comment]
@dhruvpal05 issue assigned to you, 
you can create a PR after doing the necessary changes

**Comment by nikunjgupta609** [comment]
Please sir assign me this issue.

**Comment by dhruvpal05** [comment]
#48 here made a PR do review it @dev-AshishRanjan
