### ISSUE TITLE
Adding responsiveness to website

### ISSUE THREAD

**Issue by maitri-vv** [dev-AshishRanjan/Hacktoberfest-frontend#46]
the components arent responsive enough for small screen sizes...please assign this under hacktoberfest label :)

**Comment by dev-AshishRanjan** [comment]
@maitri-vv ,
some people may also be working on this repo, **but not on this issue**
so please `pull` before `push`, to avoid any merge conflits (in any files) 👍🏽

steps : 
1. made changes
2. commit
3. pull : `git pull origin dev`
4. push

**Comment by dev-AshishRanjan** [comment]
CLOSED BY #47
