### ISSUE TITLE
Repository is again excluded from Hacktoberfest

### ISSUE THREAD

**Issue by pandeydhruv2001** [dev-AshishRanjan/Hacktoberfest-Frontend#47]

**Comment by dev-AshishRanjan** [comment]
@pandeydhruv2001 ,
I have contacted the Hacktoberfest Team regarding the issue and am waiting for their reply

**Comment by dev-AshishRanjan** [comment]
You can also checkout our [Idea-Arca](https://github.com/dev-AshishRanjan/Idea-Arca), the project idea bank for any languages, for open-source contributions.
This repo is in hacktoberfest

Happy Contributing season!
Keep up the good work!
